In [13]:
#To Confirm Accuracy Visit :
#https://rna.informatik.uni-freiburg.de/Teaching/index.jsp?toolName=Needleman-Wunsch
'''
s1=input().upper()
s2=input().upper()

#s1='AATCG'
#s2='AACG'

#s1='CGCTCGCT'
#s2='CACTCGT'

#s1='CTTCA'
#s2='CTACA'

Rs=True

for i in s1:
    if i not in 'ACGTU':
            Rs=False
            break
if(Rs):            
    for i in s2:
        if i not in 'ACGTU':
                Rs=False
                break   
            
if Rs ==False:
    print('Enter DNA or RNA only!')
else:
    print('Pass')
'''

Pass


In [1]:
import numpy as np

#s1='CG'
#s2='CA'

#s1='AATCG'
#s2='AACG'


#s1='AGGGCT'
#s2='AGGCA'

s1='CGCTCGCT'
s2='CACTCGT'

#s1='CGCT'
#s2='TCGC'

print(s1,s2)


matrix = np.zeros((len(s1)+2, len(s2)+2),dtype=int )

rowN,columN=matrix.shape

for i in range(2,rowN):  
    matrix[i][0]=ord(s1[i-2])
    matrix[i][1]=matrix[i-1][1]-2
    
for i in range(2,columN): 
    matrix[0][i]=ord(s2[i-2])
    matrix[1][i]=matrix[1][i-1]-2    
    
print(matrix)
print(rowN,columN)


CGCTCGCT CACTCGT
[[  0   0  67  65  67  84  67  71  84]
 [  0   0  -2  -4  -6  -8 -10 -12 -14]
 [ 67  -2   0   0   0   0   0   0   0]
 [ 71  -4   0   0   0   0   0   0   0]
 [ 67  -6   0   0   0   0   0   0   0]
 [ 84  -8   0   0   0   0   0   0   0]
 [ 67 -10   0   0   0   0   0   0   0]
 [ 71 -12   0   0   0   0   0   0   0]
 [ 67 -14   0   0   0   0   0   0   0]
 [ 84 -16   0   0   0   0   0   0   0]]
10 9


In [2]:
'''
Note that: 
#length of first_row = number of columns  
#length of first_column = number of rows
'''
#first_row=matrix[0]
#first_column=matrix[:,0]


#print(first_row)
#print(len(first_row))

#print(first_column)
#print(len(first_column))

#print('number of rows =',rowN)
#print('number of columns =',columN)



'\nNote that: \n#length of first_row = number of columns  \n#length of first_column = number of rows\n'

In [3]:
for i in range(2,rowN):   
    for j in range(2,columN):   
        left=matrix[i][j-1]-2
        up=matrix[i-1][j]-2
        diag=matrix[i-1][j-1]
        
        if(matrix[i][0]==matrix[0][j]):
            diag+=1
        else :
            diag-=1
        matrix[i][j]=max([left,up,diag])
        
print(matrix)


[[  0   0  67  65  67  84  67  71  84]
 [  0   0  -2  -4  -6  -8 -10 -12 -14]
 [ 67  -2   1  -1  -3  -5  -7  -9 -11]
 [ 71  -4  -1   0  -2  -4  -6  -6  -8]
 [ 67  -6  -3  -2   1  -1  -3  -5  -7]
 [ 84  -8  -5  -4  -1   2   0  -2  -4]
 [ 67 -10  -7  -6  -3   0   3   1  -1]
 [ 71 -12  -9  -8  -5  -2   1   4   2]
 [ 67 -14 -11 -10  -7  -4  -1   2   3]
 [ 84 -16 -13 -12  -9  -6  -3   0   3]]


In [4]:
i,j=rowN-1,columN-1
score=matrix[i][j]

align1=''
align2=''
matMis=''
path=[]

while i>=1 and j>=1:
    
    current=matrix[i][j]
    path.append(current)
    
    if(i==1 and j==1):
        break  

    if(matrix[i][0]==matrix[0][j]):
        align1+=chr(matrix[i][0])
        align2+=chr(matrix[0][j])
        matMis+='*'
        i,j=i-1,j-1

    else :
        left=matrix[i][j-1] 
        up=matrix[i-1][j]
        diag=matrix[i-1][j-1]
        
        maxi=max([left,up,diag])
        
        if(i==1):
            maxi=left

        if(maxi == left):
            align1+='_'
            align2+=chr(matrix[0][j])
            matMis+=' '
            j-=1

        elif(maxi == up):
            
            align1+=chr(matrix[i][0])
            align2+='_'
            matMis+=' '
            i-=1
            
        else:
            align1+= chr(matrix[i][0])
            align2+= chr(matrix[0][j])
            matMis+='|'
            i,j=i-1,j-1

    
print("[1] Score =",score)
print('\n[2] Alignment :\n')
print("       ",align1[::-1])
print("       ",matMis[::-1])
print("       ",align2[::-1])
print('\n[3] Path : ',path,'\n')
print("\n[4] MAtrix :\n")
print(matrix)

[1] Score = 3

[2] Alignment :

        CGCTCGCT
        *|**** *
        CACTCG_T

[3] Path :  [3, 2, 4, 3, 2, 1, 0, 1, 0] 


[4] MAtrix :

[[  0   0  67  65  67  84  67  71  84]
 [  0   0  -2  -4  -6  -8 -10 -12 -14]
 [ 67  -2   1  -1  -3  -5  -7  -9 -11]
 [ 71  -4  -1   0  -2  -4  -6  -6  -8]
 [ 67  -6  -3  -2   1  -1  -3  -5  -7]
 [ 84  -8  -5  -4  -1   2   0  -2  -4]
 [ 67 -10  -7  -6  -3   0   3   1  -1]
 [ 71 -12  -9  -8  -5  -2   1   4   2]
 [ 67 -14 -11 -10  -7  -4  -1   2   3]
 [ 84 -16 -13 -12  -9  -6  -3   0   3]]
