In [114]:
import numpy as np

#s1='CG'
#s2='CA'

#s1='AATCG'
#s2='AACG'

#s1='AGGGCT'
#s2='AGGCA'

s1='CGCTCGCT'
s2='CACTCGT'

#s1='CGCT'
#s2='TCGC'

print(s1,s2)

match=5
mismatch=-5
gap=-8

matrix = np.zeros((len(s1)+2, len(s2)+2),dtype=int )

rowN,columN=matrix.shape

for i in range(2,rowN):  
    matrix[i][0]=ord(s1[i-2])
    
for i in range(2,columN): 
    matrix[0][i]=ord(s2[i-2])
    
print(matrix)
print(rowN,columN)


CGCTCGCT CACTCGT
[[ 0  0 67 65 67 84 67 71 84]
 [ 0  0  0  0  0  0  0  0  0]
 [67  0  0  0  0  0  0  0  0]
 [71  0  0  0  0  0  0  0  0]
 [67  0  0  0  0  0  0  0  0]
 [84  0  0  0  0  0  0  0  0]
 [67  0  0  0  0  0  0  0  0]
 [71  0  0  0  0  0  0  0  0]
 [67  0  0  0  0  0  0  0  0]
 [84  0  0  0  0  0  0  0  0]]
10 9


In [115]:
for i in range(2,rowN):   
    for j in range(2,columN):   
        left=matrix[i][j-1]+gap
        up=matrix[i-1][j]+gap
        diag=matrix[i-1][j-1]
        
        if(matrix[i][0]==matrix[0][j]):
            diag+=match
        else :
            diag+=mismatch
            
        Maxi= max([left,up,diag])  
        if(Maxi >=0):
            matrix[i][j]=Maxi
        else:
            matrix[i][j]=0
print(matrix)


[[ 0  0 67 65 67 84 67 71 84]
 [ 0  0  0  0  0  0  0  0  0]
 [67  0  5  0  5  0  5  0  0]
 [71  0  0  0  0  0  0 10  2]
 [67  0  5  0  5  0  5  2  5]
 [84  0  0  0  0 10  2  0  7]
 [67  0  5  0  5  2 15  7  0]
 [71  0  0  0  0  0  7 20 12]
 [67  0  5  0  5  0  5 12 15]
 [84  0  0  0  0 10  2  4 17]]


In [116]:
matrix_del=np.delete(matrix,0,0)
matrix_del=np.delete(matrix_del,0,1)
matrix_del

maxStart=max(list(map(max, matrix_del)))
maxStart


20

In [117]:
result = np.where( matrix == maxStart)

i,j=result[0][0],result[1][0]
score=matrix[i][j]
print(i,j)
print(score)

7 7
20


In [118]:
align1=''
align2=''
matMis=''
path=[]

while matrix [i][j] != 0 :
    
    current=matrix[i][j]
    path.append(current)
    
    if(matrix[i][0]==matrix[0][j]):
        align1+=chr(matrix[i][0])
        align2+=chr(matrix[0][j])
        matMis+='*'
        i,j=i-1,j-1        
    else :
        left=matrix[i][j-1] 
        up=matrix[i-1][j]
        diag=matrix[i-1][j-1]
        
        maxi=max([left,up,diag])
        
        if(i==1):
            maxi=left

        if(maxi == left):
            align1+='_'
            align2+=chr(matrix[0][j])
            matMis+=' '
            j-=1

        elif(maxi == up):
            
            align1+=chr(matrix[i][0])
            align2+='_'
            matMis+=' '
            i-=1
            
        else:
            align1+= chr(matrix[i][0])
            align2+= chr(matrix[0][j])
            matMis+='|'
            i,j=i-1,j-1
   

path.append(0) 

print("[1] Score =",score)
print('\n[2] Alignment :\n')
print("       ",align1[::-1])
print("       ",matMis[::-1])
print("       ",align2[::-1])
print('\n[3] Path : ',path,'\n')
print("\n[4] MAtrix :\n")
print(matrix_del)

[1] Score = 20

[2] Alignment :

        CTCG
        ****
        CTCG

[3] Path :  [20, 15, 10, 5, 0] 


[4] MAtrix :

[[ 0  0  0  0  0  0  0  0]
 [ 0  5  0  5  0  5  0  0]
 [ 0  0  0  0  0  0 10  2]
 [ 0  5  0  5  0  5  2  5]
 [ 0  0  0  0 10  2  0  7]
 [ 0  5  0  5  2 15  7  0]
 [ 0  0  0  0  0  7 20 12]
 [ 0  5  0  5  0  5 12 15]
 [ 0  0  0  0 10  2  4 17]]
